### ISSUE TITLE
Hello, I would like to know how to configure this

### ISSUE THREAD

**Issue by mjarmak** [OpenInformix/informix-grafana#1]
Hello,
This plugin can save from a lot of work, can you please provide an example on how to set this up.
I tried the configuration shown in my screenshot but it returns "bad gateway".
![image](https://user-images.githubusercontent.com/40071422/106461441-10d17800-6495-11eb-9b9f-6e203b39dad6.png)

**Comment by AlexKoe** [comment]
Hi @mjarmak, based on the port number (9088) in your screenshot above it looks like that you might be trying to connect to the Informix SQLI port of your Informix server. The Informix Grafana adaptor connects through the Informix REST API instead. Please also check the first page of the README file. Please let me know if you have any additional questions.

**Comment by mjarmak** [comment]
Hi @AlexKoe ,
Alright I will try. Also the README file is currently empty :(

**Comment by AlexKoe** [comment]
@mjarmak You are right. I meant the 'README' file in the doc folder. Sorry for the confusion!

**Comment by AlexKoe** [comment]
Hi @mjarmak if its ok with you, I will close that issue.
